production:
  adapter: postgresql
  encoding: unicode
  database: bestofama
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: bestofama
  host: localhost
  pool: 5
  username: postgres
  password: password

test:
  adapter: sqlite3
  database: db/test.sqlite3